services:
  backend:
    build:
      context: ./backend
    container_name: monorepo-backend
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://root:123456@db:3306/smart_hospital
      JWT_ACCESS_SECRET: access-secret
      JWT_REFRESH_SECRET: refresh-secret

  db:
    image: mysql:8.4
    container_name: monorepo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: smart_hospital
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: