services:
  backend:
    build:
      context: ./backend
    container_name: monorepo-backend
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://admin:password@db:5432/monorepo?schema=public
      JWT_ACCESS_SECRET: access-secret
      JWT_REFRESH_SECRET: refresh-secret

  db:
    image: postgres:16
    container_name: monorepo-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: monorepo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d monorepo"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: